// <auto-generated />
namespace ECommerce_MVC_FrameWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ECommerce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ECommerce));
        
        string IMigrationMetadata.Id
        {
            get { return "202502270544580_ECommerce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
